name: Studio Distribuzioni SP5A.MI

on:
  schedule:
    - cron: "30 12 * * 1-5"
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    env:
      STOCK_SYMBOL: "SP5A.MI"
      FILE_NAME: "studio_distribuzioni_covered_call_vs_vendita_quote/SP5A.MI.json"
      START_DATE: "2023-11-02"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git pull --rebase origin main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas

      - name: Remove existing JSON file
        run: rm -f ${{ env.FILE_NAME }}
        shell: bash

      - name: Run stock value downloader
        run: python py/stock_value_downloader_2.py ${{ env.STOCK_SYMBOL }} ${{ env.FILE_NAME }} ${{ env.START_DATE }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add ${{ env.FILE_NAME }}
          git commit -m "Aggiornamento automatico del JSON per ${{ env.STOCK_SYMBOL }}" --allow-empty
          git push https://github.com/${{ github.repository }}.git HEAD:main
